### ISSUE TITLE
I made a crate based on this

### ISSUE THREAD

**Issue by remcokranenburg** [PonasKovas/gtk-glium#1]
Hi, I created the crate [gtk4_glium](https://crates.io/crates/gtk4_glium) based on the code in this repo. It's updated to Gtk4 and it's now a library. Would you like if I add your name to the README as the original author?

**Comment by PonasKovas** [comment]
Hi,

yeah sure, that would be very cool.

**Comment by remcokranenburg** [comment]
Done!
